/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.58
 * Generated at: 2020-10-10 06:43:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1599197221445L));
    _jspx_dependants.put("/print.jsp", Long.valueOf(1602312216727L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1599094467255L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;



    String region = "경상북도";
    String period = "2020년 07월";
    String megacd = "47";
    

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"euck-kr\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("    <title>데이터 기반 정책지원시스템</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- vendor css -->\r\n");
      out.write("    <link href=\"lib/@fortawesome/fontawesome-free/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"lib/ionicons/css/ionicons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"http://themepixels.me/demo/dashforge1.1/lib/select2/css/select2.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"http://www.nicebizmap.co.kr/assets/js/plugins/sweetalert2/sweetalert2.min.css\" rel=\"stylesheet\" id=\"theme-styles\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- leaflet css -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/leaflet/leaflet.css\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- DashForge CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/dashforge.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/dashforge.nice.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <header class=\"navbar navbar-header navbar-header-fixed\">\r\n");
      out.write("    \t<a href=\"\" id=\"mainMenuOpen\" class=\"burger-menu\"><i data-feather=\"menu\"></i></a>\r\n");
      out.write("    \t<div class=\"navbar-brand\">\r\n");
      out.write("      \t\t<img src=\"/dgi2/assets/img/dgi.png\" style=\"height:90%; margin-top: -5px;\"></img>\r\n");
      out.write("<!--     \t\t<a href=\"index.html\" class=\"df-logo\">dash<span>forge</span></a> -->\r\n");
      out.write("    \t</div><!-- navbar-brand -->\r\n");
      out.write("    \t<div id=\"navbarMenu\" class=\"navbar-menu-wrapper\">\r\n");
      out.write("    \t\t<div class=\"navbar-menu-header\">\r\n");
      out.write("    \t\t\t\t<img src=\"/dgi2/assets/img/dgi.png\"></img>\r\n");
      out.write("<!--     \t\t\t<a href=\"index.html\" class=\"df-logo\">dash<span>forge</span></a> -->\r\n");
      out.write("    \t\t\t<a id=\"mainMenuClose\" href=\"\"><i data-feather=\"x\"></i></a>\r\n");
      out.write("    \t\t</div><!-- navbar-menu-header -->\r\n");
      out.write("    \t\t<ul class=\"nav navbar-menu\">\r\n");
      out.write("    \t\t\t<li class=\"nav-label pd-l-20 pd-lg-l-25 d-lg-none\">Main Navigation</li>\r\n");
      out.write("\t          \t<li class=\"nav-item\"><a href=\"home.jsp\" class=\"nav-link\"><i></i> Home</a></li>\r\n");
      out.write("\t          \t<li class=\"nav-item\"><a href=\"page-population.jsp\" class=\"nav-link\"><i></i> 인구현황</a></li>\r\n");
      out.write("\t          \t<li class=\"nav-item\"><a href=\"page-income-consumption.jsp\" class=\"nav-link\"><i></i> 소득소비현황</a></li>\r\n");
      out.write("    \t\t\t<li class=\"nav-item with-sub\">\r\n");
      out.write("    \t\t\t\t<a href=\"\" class=\"nav-link\"><i></i> 기업현황</a>\r\n");
      out.write("    \t\t\t\t<ul class=\"navbar-menu-sub\">\r\n");
      out.write("    \t\t\t\t\t<li class=\"nav-sub-item\"><a href=\"page-company-1.jsp\" class=\"nav-sub-link\"><i></i>기업 개요</a></li>\r\n");
      out.write("              \t\t\t<li class=\"nav-sub-item\"><a href=\"dashboard-two.html\" class=\"nav-sub-link\"><i></i>기업 재무</a></li>\r\n");
      out.write("              \t\t\t<li class=\"nav-sub-item\"><a href=\"dashboard-three.html\" class=\"nav-sub-link\"><i></i>기업 수출입</a></li>\r\n");
      out.write("            \t\t</ul>\r\n");
      out.write("          \t\t</li>\r\n");
      out.write("          \t\t<li class=\"nav-item with-sub\">\r\n");
      out.write("            \t\t<a href=\"\" class=\"nav-link\"><i></i> 일자리현황</a>\r\n");
      out.write("            \t\t<ul class=\"navbar-menu-sub\">\r\n");
      out.write("              \t\t\t<li class=\"nav-sub-item\"><a href=\"app-calendar.html\" class=\"nav-sub-link\"><i></i>종사자 현황</a></li>\r\n");
      out.write("              \t\t\t<li class=\"nav-sub-item\"><a href=\"app-chat.html\" class=\"nav-sub-link\"><i></i>업종별 연봉 정보</a></li>\r\n");
      out.write("            \t\t</ul>\r\n");
      out.write("          \t\t</li>\r\n");
      out.write("          \t\t<li class=\"nav-item with-sub\">\r\n");
      out.write("            \t\t<a href=\"\" class=\"nav-link\"><i></i> 상권현황</a>\r\n");
      out.write("            \t\t<ul class=\"navbar-menu-sub\">\r\n");
      out.write("              \t\t\t<li class=\"nav-sub-item\"><a href=\"app-calendar.html\" class=\"nav-sub-link\"><i></i>상권 매출</a></li>\r\n");
      out.write("              \t\t\t<li class=\"nav-sub-item\"><a href=\"app-chat.html\" class=\"nav-sub-link\"><i></i>업종별 매출</a></li>\r\n");
      out.write("              \t\t\t<li class=\"nav-sub-item\"><a href=\"app-chat.html\" class=\"nav-sub-link\"><i></i>상권 소비 특성</a></li>\r\n");
      out.write("            \t\t</ul>\r\n");
      out.write("          \t\t</li>\r\n");
      out.write("\t          \t<li class=\"nav-item\"><a href=\"return false;\" class=\"nav-link\" onclick=\"Swal.fire('준비중입니다'); return false;\"><i></i> 도시재생</a></li>\r\n");
      out.write("        \t</ul>\r\n");
      out.write("      \t</div><!-- navbar-menu-wrapper -->\r\n");
      out.write("    </header><!-- navbar -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"content content-fixed\">\r\n");
      out.write("\t\t<div class=\"container pd-x-0 pd-lg-x-10 pd-xl-x-0\">\r\n");
      out.write("\t\t\t<div class=\"d-sm-flex align-items-center justify-content-between mg-b-20 mg-lg-b-25 mg-xl-b-30\">\r\n");
      out.write("\t        \t<div>\r\n");
      out.write("\t            \t<nav aria-label=\"breadcrumb\">\r\n");
      out.write("\t              \t\t<ol class=\"breadcrumb breadcrumb-style1 mg-b-10\">\r\n");
      out.write("\t                \t\t<li class=\"breadcrumb-item\">Home</li>\r\n");
      out.write("\t                \t\t<li class=\"breadcrumb-item active\" aria-current=\"page\">Dashboard</li>\r\n");
      out.write("\t              \t\t</ol>\r\n");
      out.write("\t            \t</nav>\r\n");
      out.write("\t            \t<h4 class=\"mg-b-0 tx-spacing--1\">데이터로 보는 <b>");
      out.print( region );
      out.write("</b> 현황 <span class=\"tx-color-03 tx-14\">(");
      out.print( period );
      out.write(")</span></h4>\r\n");
      out.write("\t          \t</div>\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t          \t<div class=\"d-none d-md-block none-print\">\r\n");
      out.write("\t\t            <button class=\"btn btn-sm pd-x-15 btn-white btn-uppercase\" onclick=\"excel();\"><i data-feather=\"download\" class=\"wd-10 mg-r-5\"></i> Excel</button>\r\n");
      out.write("\t\t            <button class=\"btn btn-sm pd-x-15 btn-white btn-uppercase mg-l-5\" onclick=\"print();\"><i data-feather=\"printer\" class=\"wd-10 mg-r-5\"></i> Print</button>\r\n");
      out.write("\t\t            <button class=\"btn btn-sm pd-x-15 btn-primary btn-uppercase mg-l-5\" onclick=\"mlreport();\"><i data-feather=\"file\" class=\"wd-10 mg-r-5\"></i> Generate Report</button>\r\n");
      out.write("          \t\t</div>\r\n");
      out.write("\t\t\t\t<script src=\"lib/jquery/jquery.min.js\"></script>\r\n");
      out.write("          \t\t<script type=\"text/javascript\" src=\"https://www.nicebizmap.co.kr/MLReport/js/mlreport.js\"></script>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\" src=\"https://www.nicebizmap.co.kr/MLReport/js/mlrpt.js\"></script>\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\tfunction excel() {\r\n");
      out.write("\t\t\t\t\t\tSwal.fire('엑셀다운로드');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tfunction mlreport() {\r\n");
      out.write("\t\t\t\t\t\tMLReportJS.SetCookie(document.cookie);\r\n");
      out.write("\t\t\t\t        PreviewDlgURL();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// ML REPORT\r\n");
      out.write("\t\t\t\t\tvar MLReportLicenseURL = \"https://www.nicebizmap.co.kr\" + \"/MLReport/WEYFFFBI8AZHMNQ.pwl\";\r\n");
      out.write("\t\t\t\t\tfunction PreviewDlgURL() {\r\n");
      out.write("\t\t\t\t\t    MLReportJS.Ready(null, function(version) {\r\n");
      out.write("\t\t\t\t\t\t\tvar region = $('.select2-region option:selected').text();\r\n");
      out.write("\t\t\t\t\t\t\tvar period = $('.select2-period option:selected').text();\r\n");
      out.write("\t\t\t\t\t\t\tvar regionVal = $('.select2-region option:selected').val();\r\n");
      out.write("\t\t\t\t\t\t\tvar periodVal = $('.select2-period option:selected').val();\r\n");
      out.write("\t\t\t\t\t        var pathname = window.location.pathname,\r\n");
      out.write("\t\t\t\t\t            urlList = '';\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t        MLReportJS.DelayPrint = true;\r\n");
      out.write("\t\t\t\t\t        MLReportJS.License = MLReportLicenseURL;\r\n");
      out.write("// \t\t\t\t\t        MLReportJS.EnableScript= false;\r\n");
      out.write("// \t\t\t\t\t        MLReportJS.PrintRate = 0.95;\r\n");
      out.write("\t\t\t\t\t\t    MLReportJS.SetCookie(document.cookie);\r\n");
      out.write("\t\t\t\t\t        if (pathname.indexOf('home') > -1) {\r\n");
      out.write("\t\t\t\t\t        \turlList = \"http://localhost:8030/dgi2/home.jsp\";\r\n");
      out.write("\t\t\t\t\t        \t\r\n");
      out.write("\t\t\t\t\t\t        MLReportJS.PreviewDlgURL(urlList);\r\n");
      out.write("\t\t\t\t\t        } else if (pathname.indexOf('page-company-1') > -1) {\r\n");
      out.write("\t\t\t\t\t        \tdebugger;\r\n");
      out.write("\t\t\t\t\t        \turlList = \"\"\r\n");
      out.write("\t\t\t\t                    + \"http://localhost:8030/dgi2/page-company-1.jsp;\"\r\n");
      out.write("\t\t\t\t            \t;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t        MLReportJS.PreviewDlg(document);\r\n");
      out.write("\t\t\t\t\t        } else if (pathname.indexOf('page-income-consumption') > -1) {\r\n");
      out.write("\t\t\t\t\t        \turlList = \"\"\r\n");
      out.write("\t\t\t\t                    + \"http://localhost:8030/dgi2/page-income-consumption.jsp?region=\" + region + \"&period=\" + period\r\n");
      out.write("\t\t\t\t                    + \"&regionVal=\" + regionVal + \"&periodVal=\" + periodVal + \";\"\r\n");
      out.write("\t\t\t\t            \t;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t        MLReportJS.PreviewDlgURL(urlList);\r\n");
      out.write("\t\t\t\t\t        }\r\n");
      out.write("\t\t\t\t\t            \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t    });\r\n");
      out.write("\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t</script>");
      out.write("\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        \r\n");
      out.write("\t    \t");



      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t          \t\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <PRNOFF>\r\n");
      out.write("        <div class=\"row row-xs none-print\">\r\n");
      out.write("          <div class=\"col-lg-12 col-xl-12 mg-t-10 mg-b-10\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("              <div class=\"card-header2 pd-y-20 d-md-flex align-items-center justify-content-between\" style=\"padding:0;\">\r\n");
      out.write("\r\n");
      out.write("<!--           \t\t<div class=\"col-sm-6 col-lg-6 col-xl-6 mg-t-10\"> -->\r\n");
      out.write("              \t<div data-label=\"지역 선택\" class=\"df-example demo-forms2\" style=\"width:50%;\">\r\n");
      out.write("\t\t          <div class=\"wd-md-100p\">\r\n");
      out.write("\t\t            <select class=\"form-control select2-region\">\r\n");
      out.write("\t\t              <option value=\"47\">경상북도</option>\r\n");
      out.write("\t\t              <option value=\"4711\">경상북도 포항시</option>\r\n");
      out.write("\t\t              <option value=\"4773\">경상북도 의성군</option>\r\n");
      out.write("\t\t              <option value=\"4777\">경상북도 영덕군</option>\r\n");
      out.write("\t\t              <option value=\"4717\">경상북도 안동시</option>\r\n");
      out.write("\t\t              <option value=\"4784\">경상북도 성주군</option>\r\n");
      out.write("\t\t              <option value=\"4713\">경상북도 경주시</option>\r\n");
      out.write("\t\t            </select>\r\n");
      out.write("\t\t          </div>\r\n");
      out.write("\t\t        </div><!-- df-example -->\r\n");
      out.write("<!-- \t\t        </div> -->\r\n");
      out.write("<!--           \t\t<div class=\"col-sm-6 col-lg-6 col-xl-6 mg-t-10\"> -->\r\n");
      out.write("              \t<div data-label=\"기준년월 선택\" class=\"df-example demo-forms\" style=\"width:50%;\">\r\n");
      out.write("\t\t          <div class=\"wd-md-100p\">\r\n");
      out.write("\t\t            <select class=\"form-control select2-period\">\r\n");
      out.write("\t\t              <option value=\"202007\">2020년 07월</option>\r\n");
      out.write("\t\t              <option value=\"202006\">2020년 06월</option>\r\n");
      out.write("\t\t              <option value=\"202005\">2020년 05월</option>\r\n");
      out.write("\t\t              <option value=\"202004\">2020년 04월</option>\r\n");
      out.write("\t\t              <option value=\"202003\">2020년 03월</option>\r\n");
      out.write("\t\t              <option value=\"202002\">2020년 02월</option>\r\n");
      out.write("\t\t              <option value=\"202001\">2020년 01월</option>\t\t              \r\n");
      out.write("\t\t              <option value=\"201912\">2019년 12월</option>\r\n");
      out.write("\t\t              <option value=\"201911\">2019년 11월</option>\r\n");
      out.write("\t\t              <option value=\"201910\">2019년 10월</option>\r\n");
      out.write("\t\t              <option value=\"201909\">2019년 09월</option>\r\n");
      out.write("\t\t              <option value=\"201908\">2019년 08월</option>\r\n");
      out.write("\t\t              <option value=\"201907\">2019년 07월</option>\r\n");
      out.write("\t\t              <option value=\"201906\">2019년 06월</option>\r\n");
      out.write("\t\t              <option value=\"201905\">2019년 05월</option>\r\n");
      out.write("\t\t              <option value=\"201904\">2019년 04월</option>\r\n");
      out.write("\t\t              <option value=\"201903\">2019년 03월</option>\r\n");
      out.write("\t\t              <option value=\"201902\">2019년 02월</option>\r\n");
      out.write("\t\t              <option value=\"201901\">2019년 01월</option>\t\t              \r\n");
      out.write("\t\t              <option value=\"201812\">2018년 12월</option>\r\n");
      out.write("\t\t              <option value=\"201811\">2018년 11월</option>\r\n");
      out.write("\t\t              <option value=\"201810\">2018년 10월</option>\r\n");
      out.write("\t\t              <option value=\"201809\">2018년 09월</option>\r\n");
      out.write("\t\t              <option value=\"201808\">2018년 08월</option>\r\n");
      out.write("\t\t              <option value=\"201807\">2018년 07월</option>\r\n");
      out.write("\t\t              <option value=\"201806\">2018년 06월</option>\r\n");
      out.write("\t\t              <option value=\"201805\">2018년 05월</option>\r\n");
      out.write("\t\t              <option value=\"201804\">2018년 04월</option>\r\n");
      out.write("\t\t              <option value=\"201803\">2018년 03월</option>\r\n");
      out.write("\t\t              <option value=\"201802\">2018년 02월</option>\r\n");
      out.write("\t\t              <option value=\"201801\">2018년 01월</option>\t\t              \r\n");
      out.write("\t\t              <option value=\"201712\">2017년 12월</option>\r\n");
      out.write("\t\t              <option value=\"201711\">2017년 11월</option>\r\n");
      out.write("\t\t              <option value=\"201710\">2017년 10월</option>\r\n");
      out.write("\t\t              <option value=\"201709\">2017년 09월</option>\r\n");
      out.write("\t\t              <option value=\"201708\">2017년 08월</option>\r\n");
      out.write("\t\t              <option value=\"201707\">2017년 07월</option>\r\n");
      out.write("\t\t              <option value=\"201706\">2017년 06월</option>\r\n");
      out.write("\t\t              <option value=\"201705\">2017년 05월</option>\r\n");
      out.write("\t\t              <option value=\"201704\">2017년 04월</option>\r\n");
      out.write("\t\t              <option value=\"201703\">2017년 03월</option>\r\n");
      out.write("\t\t              <option value=\"201702\">2017년 02월</option>\r\n");
      out.write("\t\t              <option value=\"201701\">2017년 01월</option>\t\t              \r\n");
      out.write("\t\t              <option value=\"201612\">2016년 12월</option>\r\n");
      out.write("\t\t              <option value=\"201611\">2016년 11월</option>\r\n");
      out.write("\t\t              <option value=\"201610\">2016년 10월</option>\r\n");
      out.write("\t\t              <option value=\"201609\">2016년 09월</option>\r\n");
      out.write("\t\t              <option value=\"201608\">2016년 08월</option>\r\n");
      out.write("\t\t              <option value=\"201607\">2016년 07월</option>\r\n");
      out.write("\t\t              <option value=\"201606\">2016년 06월</option>\r\n");
      out.write("\t\t              <option value=\"201605\">2016년 05월</option>\r\n");
      out.write("\t\t              <option value=\"201604\">2016년 04월</option>\r\n");
      out.write("\t\t              <option value=\"201603\">2016년 03월</option>\r\n");
      out.write("\t\t              <option value=\"201602\">2016년 02월</option>\r\n");
      out.write("\t\t              <option value=\"201601\">2016년 01월</option>\r\n");
      out.write("\t\t            </select>\r\n");
      out.write("\t\t          </div>\r\n");
      out.write("\t\t        </div><!-- df-example -->\r\n");
      out.write("<!--               \t</div> -->\r\n");
      out.write("\t\t        \r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- card-header -->\r\n");
      out.write("            </div><!-- card -->\r\n");
      out.write("          </div>\r\n");
      out.write("        </div><!-- row -->\r\n");
      out.write("\t\t</PRNOFF>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \t<div class=\"row row-xs\">\r\n");
      out.write("          \t\t<div class=\"col-print col-sm-6 col-lg-4 mg-t-10 mg-sm-t-0\">\r\n");
      out.write("            \t\t<div class=\"card card-body\">\r\n");
      out.write("              \t\t\t<h6 class=\"tx-uppercase tx-14 tx-spacing-1 tx-color-02 tx-semibold mg-b-8\">기업매출</h6>\r\n");
      out.write("              \t\t\t<div class=\"d-flex d-lg-block d-xl-flex align-items-end\">\r\n");
      out.write("                \t\t\t<h3 class=\"tx-normal tx-rubik mg-b-0 mg-r-5 lh-1\">{12,500}억</h3>\r\n");
      out.write("                \t\t\t<p class=\"tx-12 tx-color-03 mg-b-0\"><span class=\"tx-medium tx-success\">{10}% <i class=\"icon ion-md-arrow-up\"></i></span> 전월대비</p>\r\n");
      out.write("              \t\t\t</div>\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("          \t\t</div><!-- col -->\r\n");
      out.write("          \t\t<div class=\"col-print col-sm-6 col-lg-4 mg-t-10 mg-sm-t-0\">\r\n");
      out.write("            \t\t<div class=\"card card-body\">\r\n");
      out.write("              \t\t\t<h6 class=\"tx-uppercase tx-14 tx-spacing-1 tx-color-02 tx-semibold mg-b-8\">소상공인매출</h6>\r\n");
      out.write("              \t\t\t<div class=\"d-flex d-lg-block d-xl-flex align-items-end\">\r\n");
      out.write("                \t\t\t<h3 class=\"tx-normal tx-rubik mg-b-0 mg-r-5 lh-1\">{7,500}억</h3>\r\n");
      out.write("                \t\t\t<p class=\"tx-12 tx-color-03 mg-b-0\"><span class=\"tx-medium tx-danger\">{5}% <i class=\"icon ion-md-arrow-down\"></i></span> 전월대비</p>\r\n");
      out.write("              \t\t\t</div>\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("          \t\t</div><!-- col -->\r\n");
      out.write("\t\t        <div class=\"col-print col-sm-6 col-lg-4 mg-t-10 mg-lg-t-0\">\r\n");
      out.write("\t\t            <div class=\"card card-body\">\r\n");
      out.write("\t\t              \t<h6 class=\"tx-uppercase tx-14 tx-spacing-1 tx-color-02 tx-semibold mg-b-8\">주거인구</h6>\r\n");
      out.write("\t\t              \t<div class=\"d-flex d-lg-block d-xl-flex align-items-end\">\r\n");
      out.write("\t\t                \t<h3 class=\"tx-normal tx-rubik mg-b-0 mg-r-5 lh-1\">{302}만명</h3>\r\n");
      out.write("\t\t                \t<p class=\"tx-12 tx-color-03 mg-b-0\"><span class=\"tx-medium tx-success\">{1}% <i class=\"icon ion-md-arrow-up\"></i></span> 전월대비</p>\r\n");
      out.write("\t\t              \t</div>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t        </div><!-- col -->\r\n");
      out.write("          \t\t<div class=\"col-print col-sm-6 col-lg-4 mg-t-10 mg-lg-t-10\">\r\n");
      out.write("            \t\t<div class=\"card card-body\">\r\n");
      out.write("            \t\t\t<h6 class=\"tx-uppercase tx-14 tx-spacing-1 tx-color-02 tx-semibold mg-b-8\">기업일자리</h6>\r\n");
      out.write("            \t\t\t<div class=\"d-flex d-lg-block d-xl-flex align-items-end\">\r\n");
      out.write("            \t\t\t\t<h3 class=\"tx-normal tx-rubik mg-b-0 mg-r-5 lh-1\">{340,120}명</h3>\r\n");
      out.write("            \t\t\t\t<p class=\"tx-12 tx-color-03 mg-b-0\"><span class=\"tx-medium tx-success\">{17}% <i class=\"icon ion-md-arrow-up\"></i></span> 전월대비</p>\r\n");
      out.write("            \t\t\t</div>\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t</div><!-- col -->\r\n");
      out.write("            \t<div class=\"col-print col-sm-6 col-lg-4 mg-t-10 mg-lg-t-10\">\r\n");
      out.write("            \t\t<div class=\"card card-body\">\r\n");
      out.write("            \t\t\t<h6 class=\"tx-uppercase tx-14 tx-spacing-1 tx-color-02 tx-semibold mg-b-8\">유입인구 소비</h6>\r\n");
      out.write("            \t\t\t<div class=\"d-flex d-lg-block d-xl-flex align-items-end\">\r\n");
      out.write("            \t\t\t\t<h3 class=\"tx-normal tx-rubik mg-b-0 mg-r-5 lh-1\">{2,600}만건</h3>\r\n");
      out.write("            \t\t\t\t<p class=\"tx-12 tx-color-03 mg-b-0\"><span class=\"tx-medium tx-danger\">{7}% <i class=\"icon ion-md-arrow-down\"></i></span> 전월대비</p>\r\n");
      out.write("            \t\t\t</div>\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t</div><!-- col -->\r\n");
      out.write("            \t<div class=\"col-print col-sm-6 col-lg-4 mg-t-10 mg-lg-t-10\">\r\n");
      out.write("            \t\t<div class=\"card card-body\">\r\n");
      out.write("            \t\t\t<h6 class=\"tx-uppercase tx-14 tx-spacing-1 tx-color-02 tx-semibold mg-b-8\">주거인구소득</h6>\r\n");
      out.write("            \t\t\t<div class=\"d-flex d-lg-block d-xl-flex align-items-end\">\r\n");
      out.write("            \t\t\t\t<h3 class=\"tx-normal tx-rubik mg-b-0 mg-r-5 lh-1\">{305}만원</h3>\r\n");
      out.write("            \t\t\t\t<p class=\"tx-12 tx-color-03 mg-b-0\"><span class=\"tx-medium tx-success\">{7}% <i class=\"icon ion-md-arrow-up\"></i></span> 전반기대비</p>\r\n");
      out.write("            \t\t\t</div>\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t</div><!-- col -->\r\n");
      out.write("            </div><!-- row -->\r\n");
      out.write("\r\n");
      out.write("\t        <div class=\"row row-xs\">\r\n");
      out.write("\t        \t<div class=\"col-lg-12 col-xl-12 mg-t-10\">\r\n");
      out.write("\t        \t\t<div class=\"card\">\r\n");
      out.write("\t        \t\t\t<div class=\"card-body pos-relative pd-0\">\r\n");
      out.write("\t        \t\t\t\t<div id=\"map\" style=\"background: #ffffff; height: 484px; width: 100%;\"></div>\r\n");
      out.write("<!-- \t        \t\t\t\t<iframe src=\"map.jsp\" frameborder=\"0\" style=\"width: 100%; height: 500px;\" ></iframe> -->\r\n");
      out.write("\t        \t\t\t</div><!-- card-body -->\r\n");
      out.write("\t        \t\t</div><!-- card -->\r\n");
      out.write("\t        \t</div>\r\n");
      out.write("\t        </div><!-- row -->\r\n");
      out.write("      \t</div><!-- container -->\r\n");
      out.write("    </div><!-- content -->\r\n");
      out.write("\r\n");
      out.write("    <script src=\"lib/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/feather-icons/feather.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/perfect-scrollbar/perfect-scrollbar.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/chart.js/Chart.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"http://themepixels.me/demo/dashforge1.1/lib/select2/js/select2.min.js\"></script>\r\n");
      out.write("    <script src=\"http://www.nicebizmap.co.kr/assets/js/plugins/sweetalert2/sweetalert2.min.js\"></script>\r\n");
      out.write("    <script src=\"http://www.nicebizmap.co.kr/assets/js/plugins/sweetalert2/polyfill.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("\t<script type=\"text/javascript\" src=\"assets/js/leaflet/leaflet.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"assets/js/leaflet/proj4.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"assets/js/leaflet/proj4leaflet.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("    var _mega_cd_ = '");
      out.print( megacd );
      out.write("';\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"assets/js/dashforge.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/dashforge.nice.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t'use strict'\r\n");
      out.write("\r\n");
      out.write("\t\t// 선택 메뉴 활성화\r\n");
      out.write("\t\tsetNavbarMenu(0);\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t// * ------------------------------------------------------------------------------------------\r\n");
      out.write("    // * 지도 시작\r\n");
      out.write("    // * ------------------------------------------------------------------------------------------\r\n");
      out.write("\t\r\n");
      out.write("\tvar geojson;\r\n");
      out.write("\tvar ip = '10.81.100.131';\r\n");
      out.write("\r\n");
      out.write("\tfunction getColor(d) {\r\n");
      out.write("\t    return d > 6000 ? '#800026' :\r\n");
      out.write("\t           d > 5000 ? '#BD0026' :\r\n");
      out.write("\t           d > 4000 ? '#E31A1C' :\r\n");
      out.write("\t           d > 3000 ? '#FC4E2A' :\r\n");
      out.write("\t           d > 2000 ? '#FD8D3C' :\r\n");
      out.write("\t           d > 1000 ? '#FEB24C' :\r\n");
      out.write("\t           d >    0 ? '#69b2f8' :\r\n");
      out.write("\t                      '#fdfdfd' ;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 선택 가능 feature 스타일\r\n");
      out.write("\tconst activeStyle = {\r\n");
      out.write("\t\tfillColor: '#0168fa',\r\n");
      out.write("\t\tfillOpacity: 0.5,\r\n");
      out.write("\t\tcolor: '#ffffff',\r\n");
      out.write("\t\tweight: 1,\r\n");
      out.write("\t\topacity: 1,\r\n");
      out.write("\t\tdashArray: ''\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tconst highlightStyle = {\r\n");
      out.write("\t\tfillColor: '#ffda1a',\r\n");
      out.write("\t\tfillOpacity: 0.8,\r\n");
      out.write("\t\tcolor: '#ffffff',\r\n");
      out.write("\t\tweight: 1,\r\n");
      out.write("\t\topacity: 1,\r\n");
      out.write("\t\tdashArray: ''\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 선택 불가능 feature 스타일\r\n");
      out.write("\tconst inactiveStyle = {\r\n");
      out.write("\t\tfillColor: '#8392a5',\r\n");
      out.write("\t\tfillOpacity: 0.5,\r\n");
      out.write("\t\tcolor: '#ffffff',\r\n");
      out.write("\t\tweight: 1,\r\n");
      out.write("\t\topacity: 1,\r\n");
      out.write("\t\tdashArray: ''\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 최초 스타일 세팅\r\n");
      out.write("\tfunction setStyle(feature) {\r\n");
      out.write("\r\n");
      out.write("\t\tvar style;\r\n");
      out.write("\t    if (feature.properties.MEGA_CD == _mega_cd_) {\r\n");
      out.write("\t    \tstyle = activeStyle;\r\n");
      out.write("\t    } else {\r\n");
      out.write("\t    \tstyle = inactiveStyle;\r\n");
      out.write("\t    }\r\n");
      out.write("\r\n");
      out.write("\t    return style;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction zoomToFeature(e) {\r\n");
      out.write("//\t \tmap.fitBounds(e.target.getBounds());\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// add layer-event-listener\r\n");
      out.write("\tfunction onEachFeature(feature, layer) {\r\n");
      out.write("\r\n");
      out.write("\t\t// 활성화 지역만 이벤트 등록\r\n");
      out.write("\t\tif (feature.properties.MEGA_CD == _mega_cd_) {\r\n");
      out.write("\t\t    layer.on({\r\n");
      out.write("\t\t        mouseover: highlightFeature,\r\n");
      out.write("\t\t        mouseout: resetHighlight,\r\n");
      out.write("\t\t        click: clickToFeature\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// mouseover event-lestener\r\n");
      out.write("\tvar popup;\r\n");
      out.write("\tfunction highlightFeature(e) {\r\n");
      out.write("\r\n");
      out.write("\t\t// 현재 마우스오버 레이어 스타일 적용\r\n");
      out.write("\t\te.target.setStyle(highlightStyle);\r\n");
      out.write("\r\n");
      out.write("\t\t// 현재 마우스오버 레이어 팝업 띄우기\r\n");
      out.write("\t\tpopup = L.popup();\r\n");
      out.write("\t    popup.setLatLng(e.latlng)\r\n");
      out.write("\t    \t.setContent(e.target.feature.properties.CTY_NM)\r\n");
      out.write("\t    \t.openOn(map);\r\n");
      out.write("\r\n");
      out.write("\t    if (!L.Browser.ie && !L.Browser.opera && !L.Browser.edge) {\r\n");
      out.write("\t    \te.target.bringToFront();\r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// mouseout event-lestener\r\n");
      out.write("\tfunction resetHighlight(e) {\r\n");
      out.write("\r\n");
      out.write("\t\t// 선택된 레이어가 없으면 현재 마우스오버 레이어 스타일 초기화\r\n");
      out.write("\t\tif (selectedLayer === null)\r\n");
      out.write("\t\t\te.target.setStyle(activeStyle);\r\n");
      out.write("\t\t// 선택된 레이어가 있으며 현재 마우스오버 레이어와 선택된 레이어가 다르면 스타일 초기화\r\n");
      out.write("\t\telse if (selectedLayer.target.feature.properties.CTY_CD != e.target.feature.properties.CTY_CD)\r\n");
      out.write("\t\t\te.target.setStyle(activeStyle);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tpopup.onRemove(map);\r\n");
      out.write("\r\n");
      out.write("\t    if (!L.Browser.ie && !L.Browser.opera && !L.Browser.edge) {\r\n");
      out.write("\t    \te.target.bringToFront();\r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tvar selectedLayer = null;\r\n");
      out.write("\tfunction clickToFeature(e) {\r\n");
      out.write("\r\n");
      out.write("\t\t// 이전 선택 레이어 스타일 초기화\r\n");
      out.write("\t\tif (selectedLayer != null)\r\n");
      out.write("\t\t\tselectedLayer.target.setStyle(activeStyle);\r\n");
      out.write("\r\n");
      out.write("\t\t// 현재 선택 레이어 스타일 적용\r\n");
      out.write("\t\te.target.setStyle(highlightStyle);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 현재 선택 레이어 정보 저장\r\n");
      out.write("\t\tselectedLayer = e;\r\n");
      out.write("\r\n");
      out.write("\t\t// 현재 선택 레이어 팝업 띄우기\r\n");
      out.write("\t\tpopup = L.popup();\r\n");
      out.write("\t    popup.setLatLng(e.latlng)\r\n");
      out.write("\t    \t.setContent(e.target.feature.properties.CTY_NM)\r\n");
      out.write("\t    \t.openOn(map);\r\n");
      out.write("\r\n");
      out.write("\t    // selectbox option change\r\n");
      out.write("\t    changeSelectBox(e);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction changeSelectBox(e) {\r\n");
      out.write("\t\tvar cty_cd = e.target.feature.properties.CTY_CD;\r\n");
      out.write("\t\t\r\n");
      out.write("\t    parent.$('.select2-region').val(cty_cd);\r\n");
      out.write("\t    parent.$('.select2-region').select2().trigger('change');\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tvar map,\r\n");
      out.write("\tpolygon,\r\n");
      out.write("\tEPSG0000 = '+proj=tmerc +lat_0=38.0 +lon_0=128.0 +x_0=400000.0 +y_0=600000.0 +k=0.9999 +ellps=bessel +a=6377397.155 +b=6356078.9628181886 +units=m +towgs84=-115.80,474.99,674.11,1.16,-2.31,-1.63,6.43',\r\n");
      out.write("\tEPSG4326 = '+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs' ;\r\n");
      out.write("\r\n");
      out.write("\t// EPSG0000 -> EPSG4326 경위도 좌표계(WGS84)\r\n");
      out.write("\t//var new_center = proj4(EPSG0000, EPSG4326, [238418, 92335]);\r\n");
      out.write("\tmap = L.map('map', {\r\n");
      out.write("\tcenter: [35.86, 127.14],\r\n");
      out.write("\tminZoom: 8,\r\n");
      out.write("\tmaxZoom: 13\r\n");
      out.write("\t});\r\n");
      out.write("\t//map.scrollWheelZoom.disable();\r\n");
      out.write("\r\n");
      out.write("\tvar bizmapUrl = 'http://map.nicebizmap.co.kr:38080/TileMap/{z}/{y}/{x}.png';\r\n");
      out.write("\tL.tileLayer(bizmapUrl, { attribution: \"Map data www.nicebizmap.co.kr\", maxZoom: 13, minZoom: 8 }).addTo(map);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tvar data, geojson_nm, response;\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype     : 'post',\r\n");
      out.write("\t\turl      : '/dgi/tbshp_cty_tk.geojson',\r\n");
      out.write("\t\tdataType : 'json',\r\n");
      out.write("\t\tasync    : false,\r\n");
      out.write("\t\tsuccess  : function(response, status, request) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 전역변수\r\n");
      out.write("\t\t\tgeojson_nm = response.name;\r\n");
      out.write("\r\n");
      out.write("\t\t\t// filter\r\n");
      out.write("\t\t\ttk = response.features.filter(function(feature) {\r\n");
      out.write("\t\t\t\tvar mega_cd = feature.properties.MEGA_CD\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\tif (mega_cd == 27 || mega_cd == 47) return feature.properties.CTY_CD;\r\n");
      out.write("\t\t\t\telse return null;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tt = response.features.filter(function(feature) {\r\n");
      out.write("\t\t\t\tvar mega_cd = feature.properties.MEGA_CD\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\tif (mega_cd == 27) return feature.properties.CTY_CD;\r\n");
      out.write("\t\t\t\telse return null;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t    geojson = L.geoJson(tk, {\r\n");
      out.write("\t\t    \tstyle: setStyle,\r\n");
      out.write("\t\t    \tonEachFeature: onEachFeature\r\n");
      out.write("\t\t    }).addTo(map);\r\n");
      out.write("\r\n");
      out.write("\t\t    polygon = L.geoJson(tk);\r\n");
      out.write("\t\t    polygon_t = L.geoJson(t);\r\n");
      out.write("\t\t    if (_mega_cd_ == 27) {\r\n");
      out.write("\t\t    \tmap.fitBounds(polygon_t.getBounds());\r\n");
      out.write("\t\t    } else {\r\n");
      out.write("\t\t    \tmap.fitBounds(polygon.getBounds());\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tcomplete : function() {},\r\n");
      out.write("\t\terror : function(request, status, error) { // 에러\r\n");
      out.write("\t\t    alert('문제가 발생하였습니다. 잠시후 다시 이용해주세요.');\r\n");
      out.write("\t\t    return;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction zoom_feature() {\r\n");
      out.write("\t\tmap.fitBounds(polygon.getBounds());\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\t// * ------------------------------------------------------------------------------------------\r\n");
      out.write("    // * 지도 종료\r\n");
      out.write("    // * ------------------------------------------------------------------------------------------\r\n");
      out.write("\t\r\n");
      out.write("\t// 출력\r\n");
      out.write("\tif (typeof MLReportStartPrint == 'function') {\r\n");
      out.write("\t\tsetTimeout(\"callTimeoutFunction()\", 500);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar callTimeoutFunction = function() {\r\n");
      out.write("\t\tMLReportStartPrint();\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
