/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.58
 * Generated at: 2020-10-10 07:42:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class page_002dcompany_002d1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1599197221445L));
    _jspx_dependants.put("/print.jsp", Long.valueOf(1602315673223L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1599094467255L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;



    String region = request.getParameter("region") == null ? "경상북도" : request.getParameter("region");
    String period = request.getParameter("period") == null ? "2020년 07월" : request.getParameter("period");
    String regionVal = request.getParameter("regionVal") == null ? "47" : request.getParameter("regionVal");
    String periodVal = request.getParameter("periodVal") == null ? "202007" : request.getParameter("periodVal");
    
//     String region = aaa;
//     String period = "2020년 07월";
    
    
    String ctxLabel = "['19.07', '19.08', '19.09', '19.10', '19.11', '19.12', '20.01', '20.02', '20.03', '20.04', '20.05', '20.06', '20.07']";
    String ctxData1 = "[-33, 20, 60, 50, 45, 50, 60, 70, 40, 45, 35, 25, 30]";
    String ctxData2 = "[44, 10, 40, 30, 40, 60, 55, 45, 35, 30, 20, 15, 20]";
    

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"euck-kr\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("    <title>데이터 기반 정책지원시스템</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- vendor css -->\r\n");
      out.write("    <link href=\"lib/@fortawesome/fontawesome-free/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"lib/ionicons/css/ionicons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"lib/select2/css/select2.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"http://www.nicebizmap.co.kr/assets/js/plugins/sweetalert2/sweetalert2.min.css\" rel=\"stylesheet\" id=\"theme-styles\">\r\n");
      out.write("\r\n");
      out.write("    <!-- DashForge CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/dashforge.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/dashforge.nice.css\">\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <header class=\"navbar navbar-header navbar-header-fixed\">\r\n");
      out.write("    \t<a href=\"\" id=\"mainMenuOpen\" class=\"burger-menu\"><i data-feather=\"menu\"></i></a>\r\n");
      out.write("    \t<div class=\"navbar-brand\">\r\n");
      out.write("      \t\t<img src=\"/dgi2/assets/img/dgi.png\" style=\"height:90%; margin-top: -5px;\"></img>\r\n");
      out.write("<!--     \t\t<a href=\"index.html\" class=\"df-logo\">dash<span>forge</span></a> -->\r\n");
      out.write("    \t</div><!-- navbar-brand -->\r\n");
      out.write("    \t<div id=\"navbarMenu\" class=\"navbar-menu-wrapper\">\r\n");
      out.write("    \t\t<div class=\"navbar-menu-header\">\r\n");
      out.write("    \t\t\t\t<img src=\"/dgi2/assets/img/dgi.png\"></img>\r\n");
      out.write("<!--     \t\t\t<a href=\"index.html\" class=\"df-logo\">dash<span>forge</span></a> -->\r\n");
      out.write("    \t\t\t<a id=\"mainMenuClose\" href=\"\"><i data-feather=\"x\"></i></a>\r\n");
      out.write("    \t\t</div><!-- navbar-menu-header -->\r\n");
      out.write("    \t\t<ul class=\"nav navbar-menu\">\r\n");
      out.write("    \t\t\t<li class=\"nav-label pd-l-20 pd-lg-l-25 d-lg-none\">Main Navigation</li>\r\n");
      out.write("\t          \t<li class=\"nav-item\"><a href=\"home.jsp\" class=\"nav-link\"><i></i> Home</a></li>\r\n");
      out.write("\t          \t<li class=\"nav-item\"><a href=\"page-population.jsp\" class=\"nav-link\"><i></i> 인구현황</a></li>\r\n");
      out.write("\t          \t<li class=\"nav-item\"><a href=\"page-income-consumption.jsp\" class=\"nav-link\"><i></i> 소득소비현황</a></li>\r\n");
      out.write("    \t\t\t<li class=\"nav-item with-sub\">\r\n");
      out.write("    \t\t\t\t<a href=\"\" class=\"nav-link\"><i></i> 기업현황</a>\r\n");
      out.write("    \t\t\t\t<ul class=\"navbar-menu-sub\">\r\n");
      out.write("    \t\t\t\t\t<li class=\"nav-sub-item\"><a href=\"page-company-1.jsp\" class=\"nav-sub-link\"><i></i>기업 개요</a></li>\r\n");
      out.write("              \t\t\t<li class=\"nav-sub-item\"><a href=\"dashboard-two.html\" class=\"nav-sub-link\"><i></i>기업 재무</a></li>\r\n");
      out.write("              \t\t\t<li class=\"nav-sub-item\"><a href=\"dashboard-three.html\" class=\"nav-sub-link\"><i></i>기업 수출입</a></li>\r\n");
      out.write("            \t\t</ul>\r\n");
      out.write("          \t\t</li>\r\n");
      out.write("          \t\t<li class=\"nav-item with-sub\">\r\n");
      out.write("            \t\t<a href=\"\" class=\"nav-link\"><i></i> 일자리현황</a>\r\n");
      out.write("            \t\t<ul class=\"navbar-menu-sub\">\r\n");
      out.write("              \t\t\t<li class=\"nav-sub-item\"><a href=\"app-calendar.html\" class=\"nav-sub-link\"><i></i>종사자 현황</a></li>\r\n");
      out.write("              \t\t\t<li class=\"nav-sub-item\"><a href=\"app-chat.html\" class=\"nav-sub-link\"><i></i>업종별 연봉 정보</a></li>\r\n");
      out.write("            \t\t</ul>\r\n");
      out.write("          \t\t</li>\r\n");
      out.write("          \t\t<li class=\"nav-item with-sub\">\r\n");
      out.write("            \t\t<a href=\"\" class=\"nav-link\"><i></i> 상권현황</a>\r\n");
      out.write("            \t\t<ul class=\"navbar-menu-sub\">\r\n");
      out.write("              \t\t\t<li class=\"nav-sub-item\"><a href=\"app-calendar.html\" class=\"nav-sub-link\"><i></i>상권 매출</a></li>\r\n");
      out.write("              \t\t\t<li class=\"nav-sub-item\"><a href=\"app-chat.html\" class=\"nav-sub-link\"><i></i>업종별 매출</a></li>\r\n");
      out.write("              \t\t\t<li class=\"nav-sub-item\"><a href=\"app-chat.html\" class=\"nav-sub-link\"><i></i>상권 소비 특성</a></li>\r\n");
      out.write("            \t\t</ul>\r\n");
      out.write("          \t\t</li>\r\n");
      out.write("\t          \t<li class=\"nav-item\"><a href=\"return false;\" class=\"nav-link\" onclick=\"Swal.fire('준비중입니다'); return false;\"><i></i> 도시재생</a></li>\r\n");
      out.write("        \t</ul>\r\n");
      out.write("      \t</div><!-- navbar-menu-wrapper -->\r\n");
      out.write("    </header><!-- navbar -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"content content-fixed\"> \r\n");
      out.write("\t\t<div class=\"container pd-x-0 pd-lg-x-10 pd-xl-x-0\">\r\n");
      out.write("\t\t\t<div class=\"d-sm-flex align-items-center justify-content-between mg-b-20 mg-lg-b-25 mg-xl-b-30\">\r\n");
      out.write("\t        \t<div>\r\n");
      out.write("\t            \t<nav aria-label=\"breadcrumb\">\r\n");
      out.write("\t              \t\t<ol class=\"breadcrumb breadcrumb-style1 mg-b-10\">\r\n");
      out.write("\t                \t\t<li class=\"breadcrumb-item\">기업현황</li>\r\n");
      out.write("\t                \t\t<li class=\"breadcrumb-item active\" aria-current=\"page\">기업 개요</li>\r\n");
      out.write("\t              \t\t</ol>\r\n");
      out.write("\t            \t</nav>\r\n");
      out.write("\t            \t<h4 class=\"mg-b-0 tx-spacing--1\">데이터로 보는 <b>");
      out.print( region );
      out.write("</b> 현황 <span class=\"tx-color-03 tx-14\">(");
      out.print( period );
      out.write(")</span></h4>\r\n");
      out.write("\t          \t</div>\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t          \t<div class=\"d-none d-md-block none-print\">\r\n");
      out.write("\t\t            <button class=\"btn btn-sm pd-x-15 btn-white btn-uppercase\" onclick=\"excel();\"><i data-feather=\"download\" class=\"wd-10 mg-r-5\"></i> Excel</button>\r\n");
      out.write("\t\t            <button class=\"btn btn-sm pd-x-15 btn-white btn-uppercase mg-l-5\" onclick=\"print();\"><i data-feather=\"printer\" class=\"wd-10 mg-r-5\"></i> Print</button>\r\n");
      out.write("\t\t            <button class=\"btn btn-sm pd-x-15 btn-primary btn-uppercase mg-l-5\" onclick=\"mlreport();\"><i data-feather=\"file\" class=\"wd-10 mg-r-5\"></i> Generate Report</button>\r\n");
      out.write("          \t\t</div>\r\n");
      out.write("\t\t\t\t<script src=\"lib/jquery/jquery.min.js\"></script>\r\n");
      out.write("          \t\t<script type=\"text/javascript\" src=\"https://www.nicebizmap.co.kr/MLReport/js/mlreport.js\"></script>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\" src=\"https://www.nicebizmap.co.kr/MLReport/js/mlrpt.js\"></script>\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\tfunction excel() {\r\n");
      out.write("\t\t\t\t\t\tSwal.fire('엑셀다운로드');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tfunction mlreport() {\r\n");
      out.write("\t\t\t\t\t\tMLReportJS.SetCookie(document.cookie);\r\n");
      out.write("\t\t\t\t        PreviewDlgURL();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// ML REPORT\r\n");
      out.write("\t\t\t\t\tvar MLReportLicenseURL = \"https://www.nicebizmap.co.kr\" + \"/MLReport/WEYFFFBI8AZHMNQ.pwl\";\r\n");
      out.write("\t\t\t\t\tfunction PreviewDlgURL() {\r\n");
      out.write("\t\t\t\t\t    MLReportJS.Ready(null, function(version) {\r\n");
      out.write("\t\t\t\t\t\t\tvar region = $('.select2-region option:selected').text();\r\n");
      out.write("\t\t\t\t\t\t\tvar period = $('.select2-period option:selected').text();\r\n");
      out.write("\t\t\t\t\t\t\tvar regionVal = $('.select2-region option:selected').val();\r\n");
      out.write("\t\t\t\t\t\t\tvar periodVal = $('.select2-period option:selected').val();\r\n");
      out.write("\t\t\t\t\t        var pathname = window.location.pathname,\r\n");
      out.write("\t\t\t\t\t            urlList = '';\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t        MLReportJS.DelayPrint = true;\r\n");
      out.write("\t\t\t\t\t        MLReportJS.License = MLReportLicenseURL;\r\n");
      out.write("// \t\t\t\t\t        MLReportJS.EnableScript= false;\r\n");
      out.write("// \t\t\t\t\t        MLReportJS.PrintRate = 0.95;\r\n");
      out.write("\t\t\t\t\t\t    MLReportJS.SetCookie(document.cookie);\r\n");
      out.write("\t\t\t\t\t        if (pathname.indexOf('home') > -1) {\r\n");
      out.write("\t\t\t\t\t        \turlList = \"http://localhost:8030/dgi2/home.jsp\";\r\n");
      out.write("\t\t\t\t\t        \t\r\n");
      out.write("\t\t\t\t\t\t        MLReportJS.PreviewDlgURL(urlList);\r\n");
      out.write("\t\t\t\t\t        } else if (pathname.indexOf('page-company-1') > -1) {\r\n");
      out.write("\t\t\t\t\t        \tdebugger;\r\n");
      out.write("\t\t\t\t\t        \turlList = \"\"\r\n");
      out.write("\t\t\t\t                    + \"http://localhost:8030/dgi2/page-company-1.jsp?region=\" + region + \"&period=\" + period\r\n");
      out.write("\t\t\t\t                    + \"&regionVal=\" + regionVal + \"&periodVal=\" + periodVal + \";\"\r\n");
      out.write("\t\t\t\t            \t;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t        MLReportJS.PreviewDlgURL(urlList);\r\n");
      out.write("\t\t\t\t\t        } else if (pathname.indexOf('page-income-consumption') > -1) {\r\n");
      out.write("\t\t\t\t\t        \turlList = \"\"\r\n");
      out.write("\t\t\t\t                    + \"http://localhost:8030/dgi2/page-income-consumption.jsp?region=\" + region + \"&period=\" + period\r\n");
      out.write("\t\t\t\t                    + \"&regionVal=\" + regionVal + \"&periodVal=\" + periodVal + \";\"\r\n");
      out.write("\t\t\t\t            \t;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t        MLReportJS.PreviewDlgURL(urlList);\r\n");
      out.write("\t\t\t\t\t        }\r\n");
      out.write("\t\t\t\t\t            \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t    });\r\n");
      out.write("\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t</script>");
      out.write("\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        \r\n");
      out.write("\t    \t");



      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t          \t\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <PRNOFF>\r\n");
      out.write("        <div class=\"row row-xs none-print\">\r\n");
      out.write("          <div class=\"col-lg-12 col-xl-12 mg-t-10 mg-b-10\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("              <div class=\"card-header2 pd-y-20 d-md-flex align-items-center justify-content-between\" style=\"padding:0;\">\r\n");
      out.write("\r\n");
      out.write("<!--           \t\t<div class=\"col-sm-6 col-lg-6 col-xl-6 mg-t-10\"> -->\r\n");
      out.write("              \t<div data-label=\"지역 선택\" class=\"df-example demo-forms2\" style=\"width:50%;\">\r\n");
      out.write("\t\t          <div class=\"wd-md-100p\">\r\n");
      out.write("\t\t            <select class=\"form-control select2-region\">\r\n");
      out.write("\t\t              <option value=\"47\">경상북도</option>\r\n");
      out.write("\t\t              <option value=\"4711\">경상북도 포항시</option>\r\n");
      out.write("\t\t              <option value=\"4773\">경상북도 의성군</option>\r\n");
      out.write("\t\t              <option value=\"4777\">경상북도 영덕군</option>\r\n");
      out.write("\t\t              <option value=\"4717\">경상북도 안동시</option>\r\n");
      out.write("\t\t              <option value=\"4784\">경상북도 성주군</option>\r\n");
      out.write("\t\t              <option value=\"4713\">경상북도 경주시</option>\r\n");
      out.write("\t\t            </select>\r\n");
      out.write("\t\t          </div>\r\n");
      out.write("\t\t        </div><!-- df-example -->\r\n");
      out.write("<!-- \t\t        </div> -->\r\n");
      out.write("<!--           \t\t<div class=\"col-sm-6 col-lg-6 col-xl-6 mg-t-10\"> -->\r\n");
      out.write("              \t<div data-label=\"기준년월 선택\" class=\"df-example demo-forms\" style=\"width:50%;\">\r\n");
      out.write("\t\t          <div class=\"wd-md-100p\">\r\n");
      out.write("\t\t            <select class=\"form-control select2-period\">\r\n");
      out.write("\t\t              <option value=\"202007\">2020년 07월</option>\r\n");
      out.write("\t\t              <option value=\"202006\">2020년 06월</option>\r\n");
      out.write("\t\t              <option value=\"202005\">2020년 05월</option>\r\n");
      out.write("\t\t              <option value=\"202004\">2020년 04월</option>\r\n");
      out.write("\t\t              <option value=\"202003\">2020년 03월</option>\r\n");
      out.write("\t\t              <option value=\"202002\">2020년 02월</option>\r\n");
      out.write("\t\t              <option value=\"202001\">2020년 01월</option>\t\t              \r\n");
      out.write("\t\t              <option value=\"201912\">2019년 12월</option>\r\n");
      out.write("\t\t              <option value=\"201911\">2019년 11월</option>\r\n");
      out.write("\t\t              <option value=\"201910\">2019년 10월</option>\r\n");
      out.write("\t\t              <option value=\"201909\">2019년 09월</option>\r\n");
      out.write("\t\t              <option value=\"201908\">2019년 08월</option>\r\n");
      out.write("\t\t              <option value=\"201907\">2019년 07월</option>\r\n");
      out.write("\t\t              <option value=\"201906\">2019년 06월</option>\r\n");
      out.write("\t\t              <option value=\"201905\">2019년 05월</option>\r\n");
      out.write("\t\t              <option value=\"201904\">2019년 04월</option>\r\n");
      out.write("\t\t              <option value=\"201903\">2019년 03월</option>\r\n");
      out.write("\t\t              <option value=\"201902\">2019년 02월</option>\r\n");
      out.write("\t\t              <option value=\"201901\">2019년 01월</option>\t\t              \r\n");
      out.write("\t\t              <option value=\"201812\">2018년 12월</option>\r\n");
      out.write("\t\t              <option value=\"201811\">2018년 11월</option>\r\n");
      out.write("\t\t              <option value=\"201810\">2018년 10월</option>\r\n");
      out.write("\t\t              <option value=\"201809\">2018년 09월</option>\r\n");
      out.write("\t\t              <option value=\"201808\">2018년 08월</option>\r\n");
      out.write("\t\t              <option value=\"201807\">2018년 07월</option>\r\n");
      out.write("\t\t              <option value=\"201806\">2018년 06월</option>\r\n");
      out.write("\t\t              <option value=\"201805\">2018년 05월</option>\r\n");
      out.write("\t\t              <option value=\"201804\">2018년 04월</option>\r\n");
      out.write("\t\t              <option value=\"201803\">2018년 03월</option>\r\n");
      out.write("\t\t              <option value=\"201802\">2018년 02월</option>\r\n");
      out.write("\t\t              <option value=\"201801\">2018년 01월</option>\t\t              \r\n");
      out.write("\t\t              <option value=\"201712\">2017년 12월</option>\r\n");
      out.write("\t\t              <option value=\"201711\">2017년 11월</option>\r\n");
      out.write("\t\t              <option value=\"201710\">2017년 10월</option>\r\n");
      out.write("\t\t              <option value=\"201709\">2017년 09월</option>\r\n");
      out.write("\t\t              <option value=\"201708\">2017년 08월</option>\r\n");
      out.write("\t\t              <option value=\"201707\">2017년 07월</option>\r\n");
      out.write("\t\t              <option value=\"201706\">2017년 06월</option>\r\n");
      out.write("\t\t              <option value=\"201705\">2017년 05월</option>\r\n");
      out.write("\t\t              <option value=\"201704\">2017년 04월</option>\r\n");
      out.write("\t\t              <option value=\"201703\">2017년 03월</option>\r\n");
      out.write("\t\t              <option value=\"201702\">2017년 02월</option>\r\n");
      out.write("\t\t              <option value=\"201701\">2017년 01월</option>\t\t              \r\n");
      out.write("\t\t              <option value=\"201612\">2016년 12월</option>\r\n");
      out.write("\t\t              <option value=\"201611\">2016년 11월</option>\r\n");
      out.write("\t\t              <option value=\"201610\">2016년 10월</option>\r\n");
      out.write("\t\t              <option value=\"201609\">2016년 09월</option>\r\n");
      out.write("\t\t              <option value=\"201608\">2016년 08월</option>\r\n");
      out.write("\t\t              <option value=\"201607\">2016년 07월</option>\r\n");
      out.write("\t\t              <option value=\"201606\">2016년 06월</option>\r\n");
      out.write("\t\t              <option value=\"201605\">2016년 05월</option>\r\n");
      out.write("\t\t              <option value=\"201604\">2016년 04월</option>\r\n");
      out.write("\t\t              <option value=\"201603\">2016년 03월</option>\r\n");
      out.write("\t\t              <option value=\"201602\">2016년 02월</option>\r\n");
      out.write("\t\t              <option value=\"201601\">2016년 01월</option>\r\n");
      out.write("\t\t            </select>\r\n");
      out.write("\t\t          </div>\r\n");
      out.write("\t\t        </div><!-- df-example -->\r\n");
      out.write("<!--               \t</div> -->\r\n");
      out.write("\t\t        \r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- card-header -->\r\n");
      out.write("            </div><!-- card -->\r\n");
      out.write("          </div>\r\n");
      out.write("        </div><!-- row -->\r\n");
      out.write("\t\t</PRNOFF>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \t<div class=\"row row-xs\">\r\n");
      out.write("          \t\t<div class=\"col-lg-12 col-xl-12 mg-t-10\">\r\n");
      out.write("          \t\t\t<div class=\"card\">\r\n");
      out.write("              \t\t\t<div class=\"card-header d-flex align-items-start justify-content-between\">\r\n");
      out.write("                \t\t\t<h6 class=\"lh-5 mg-b-0\">* 관내 기업 현황</h6>\r\n");
      out.write("                \t\t\t<p class=\"period tx-13 tx-color-03 mg-b-0\">");
      out.print( period );
      out.write("</p>\r\n");
      out.write("              \t\t\t</div><!-- card-header -->\r\n");
      out.write("              \t\t\t<div class=\"card-body pd-y-15 pd-x-10\">\r\n");
      out.write("\t              \t\t\t<div class=\"table-responsive table-hover\">\r\n");
      out.write("\t                \t\t\t<table class=\"table mg-b-0\">\r\n");
      out.write("\t                  \t\t\t\t<thead class=\"thead-secondary\">\r\n");
      out.write("\t                    \t\t\t\t<tr>\r\n");
      out.write("\t                      \t\t\t\t\t<th scope=\"col\" class=\"text-center\">기업체수</th>\r\n");
      out.write("\t\t\t\t\t\t                    <th scope=\"col\" class=\"text-center\">종사자 총 수</th>\r\n");
      out.write("\t\t\t\t\t\t                    <th scope=\"col\" class=\"text-center\">매출총액</th>\r\n");
      out.write("\t\t\t\t\t\t                    <th scope=\"col\" class=\"text-center\">자산총계</th>\r\n");
      out.write("\t\t\t\t\t\t                    <th scope=\"col\" class=\"text-center\">전월대비 수출증감률</th>\r\n");
      out.write("\t\t\t\t\t\t                    <th scope=\"col\" class=\"text-center\">전월대비 수입증감률</th>\r\n");
      out.write("\t                    \t\t\t\t</tr>\r\n");
      out.write("\t                  \t\t\t\t</thead>\r\n");
      out.write("\t                  \t\t\t\t<tbody>\r\n");
      out.write("\t                    \t\t\t\t<tr>\r\n");
      out.write("\t                      \t\t\t\t\t<td class=\"tx-medium text-center\">{} 개</td>\r\n");
      out.write("\t                      \t\t\t\t\t<td class=\"tx-medium text-center\">{} 명</td>\r\n");
      out.write("\t                      \t\t\t\t\t<td class=\"tx-medium text-center\">{} 억원</td>\r\n");
      out.write("\t                      \t\t\t\t\t<td class=\"tx-medium text-center\">{} 억원</td>\r\n");
      out.write("\t                      \t\t\t\t\t<td class=\"tx-medium text-center\">{} %</td>\r\n");
      out.write("\t                      \t\t\t\t\t<td class=\"tx-medium text-center\">{} %</td>\r\n");
      out.write("\t                    \t\t\t\t</tr>\r\n");
      out.write("\t                  \t\t\t\t</tbody>\r\n");
      out.write("\t                \t\t\t</table>\r\n");
      out.write("\t              \t\t\t</div><!-- table-responsive -->\r\n");
      out.write("              \t\t\t</div><!-- card-body -->\r\n");
      out.write("            \t\t</div><!-- card -->\r\n");
      out.write("          \t\t</div><!-- col -->\r\n");
      out.write("        \r\n");
      out.write("          \t\t<div class=\"col-md-12 col-xl-12 mg-t-10\">\r\n");
      out.write("            \t\t<div class=\"card ht-lg-100p\">\r\n");
      out.write("              \t\t\t<div class=\"card-header d-flex align-items-center justify-content-between\">\r\n");
      out.write("              \t\t\t\t<h6 class=\"mg-b-0\">* 관내 기업 수 변동</h6>\r\n");
      out.write("              \t\t\t\t<ul class=\"list-inline d-flex mg-b-0\">\r\n");
      out.write("              \t\t\t\t\t<li class=\"list-inline-item d-flex align-items-center\">\r\n");
      out.write("              \t\t\t\t\t\t<p class=\"period tx-13 tx-color-03 mg-b-0\">");
      out.print( period );
      out.write("</p>\r\n");
      out.write("              \t\t\t\t\t</li>\r\n");
      out.write("                \t\t\t</ul>\r\n");
      out.write("              \t\t\t</div><!-- card-header -->\r\n");
      out.write("<!--               \t\t\t<div class=\"card-body\"> -->\r\n");
      out.write("                 \t\t\t<div class=\"mg-t-20 px-3\">\r\n");
      out.write("                 \t\t\t<canvas id=\"chartLine01\" style=\"position: relative; margin: auto; height:300px;\"></canvas></div>\r\n");
      out.write("<!--               \t\t\t</div> -->\r\n");
      out.write("              \t\t\t<!-- card-body -->\r\n");
      out.write("              \t\t\t<div class=\"card-body mg-t-10\">\r\n");
      out.write("\t              \t\t\t<div class=\"table-responsive table-hover\">\r\n");
      out.write("\t                \t\t\t<table class=\"table mg-b-0\">\r\n");
      out.write("\t                  \t\t\t\t<thead class=\"thead-secondary\">\r\n");
      out.write("\t                    \t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"text-center\">구분</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"text-center\">19.06</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"text-center\">19.07</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"text-center\">19.08</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"text-center\">19.09</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"text-center\">19.10</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"text-center\">19.11</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"text-center\">19.12</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"text-center\">20.01</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"text-center\">20.02</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"text-center\">20.03</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"text-center\">20.04</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"text-center\">20.05</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\" class=\"text-center\">20.06</th>\r\n");
      out.write("\t                   \t\t\t\t\t</tr>\r\n");
      out.write("\t                  \t\t\t\t</thead>\r\n");
      out.write("\t                  \t\t\t\t<tbody>\r\n");
      out.write("\t                    \t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"tx-medium text-center\" style=\"min-width:100px;\" >기업 수</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"tx-medium text-center\">{33} 개</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"tx-medium text-center\">{20} 개</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"tx-medium text-center\">{60} 개</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"tx-medium text-center\">{50} 개</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"tx-medium text-center\">{45} 개</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"tx-medium text-center\">{50} 개</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"tx-medium text-center\">{60} 개</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"tx-medium text-center\">{70} 개</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"tx-medium text-center\">{40} 개</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"tx-medium text-center\">{45} 개</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"tx-medium text-center\">{35} 개</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"tx-medium text-center\">{25} 개</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"tx-medium text-center\">{30} 개</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t                  \t\t\t\t</tbody>\r\n");
      out.write("\t                \t\t\t</table>\r\n");
      out.write("\t              \t\t\t</div><!-- table-responsive -->\r\n");
      out.write("              \t\t\t</div><!-- card-body -->\r\n");
      out.write("           \t\t\t</div>\r\n");
      out.write("          \t\t</div>\r\n");
      out.write("          \t</div><!-- row -->\r\n");
      out.write("          \t\r\n");
      out.write("      \t</div><!-- container -->\r\n");
      out.write("    </div><!-- content -->\r\n");
      out.write("\r\n");
      out.write("    <script src=\"lib/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/feather-icons/feather.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/perfect-scrollbar/perfect-scrollbar.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/chart.js/Chart.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/select2/js/select2.min.js\"></script>\r\n");
      out.write("    <script src=\"http://www.nicebizmap.co.kr/assets/js/plugins/sweetalert2/sweetalert2.min.js\"></script>\r\n");
      out.write("    <script src=\"http://www.nicebizmap.co.kr/assets/js/plugins/sweetalert2/polyfill.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"assets/js/dashforge.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/dashforge.nice.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/dashforge.chartjs.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\tvar region = '");
      out.print( regionVal );
      out.write("',\r\n");
      out.write("\t    period = '");
      out.print( periodVal );
      out.write("';\r\n");
      out.write("\r\n");
      out.write("\tvar chartjs01;\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t'use strict'\r\n");
      out.write("\r\n");
      out.write("\t\t// 선택 메뉴 활성화\r\n");
      out.write("\t\tsetNavbarMenu(3);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tchartjs01();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tvar chartjs01 = function() {\r\n");
      out.write("\r\n");
      out.write("\t\t// create chartjs.chart\r\n");
      out.write("        var ctx = document.getElementById('chartLine01');\r\n");
      out.write("        chartjs01 = new Chart(ctx, {\r\n");
      out.write("        \ttype: 'line',\r\n");
      out.write("        \tdata: {\r\n");
      out.write("        \t\tlabels: ");
      out.print( ctxLabel );
      out.write(",\r\n");
      out.write("        \t\tdatasets: [{\r\n");
      out.write("        \t\t\tdata: ");
      out.print( ctxData1 );
      out.write(",\r\n");
      out.write("        \t\t\tborderColor: '#1ce1ac',\r\n");
      out.write("        \t\t\tborderWidth: 1.2,\r\n");
      out.write("        \t\t\tfill: false\r\n");
      out.write("        \t\t}]\r\n");
      out.write("       \t\t},\r\n");
      out.write("       \t\toptions: lineOptions01\r\n");
      out.write("       \t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar reloadChartjs = function(region, period) {\r\n");
      out.write("\t\t// 분기태우는거는 테스트를 위함이며\r\n");
      out.write("\t\t// 실제 개발 때는 하나만 있으면 됨!\r\n");
      out.write("\t\tif (period === '202007') {\r\n");
      out.write("\t\t\t// chartLine01 reload\r\n");
      out.write("\t\t\tchartjs01.data.labels = ['19.07', '19.08', '19.09', '19.10', '19.11', '19.12', '20.01', '20.02', '20.03', '20.04', '20.05', '20.06', '20.07'];\r\n");
      out.write("\t\t\tchartjs01.data.datasets.forEach(function(dataset) {\r\n");
      out.write("\t\t\t\tdataset.data = [-33, 20, 60, 50, 45, 50, 60, 70, 40, 45, 35, 25, 30];\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tchartjs01.update();\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t// chartLine01 reload\r\n");
      out.write("\t\t\tchartjs01.data.labels = ['19.06', '19.07', '19.08', '19.09', '19.10', '19.11', '19.12', '20.01', '20.02', '20.03', '20.04', '20.05', '20.06'];\r\n");
      out.write("\t\t\tchartjs01.data.datasets.forEach(function(dataset) {\r\n");
      out.write("\t\t\t\tdataset.data = [44, 10, 40, 30, 40, 60, 55, 45, 35, 30, 20, 15, 20];\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tchartjs01.update();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('.period').html(period.substring(0,4) + '년 ' + period.substring(4) + '월');\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t// 출력\r\n");
      out.write("\tif (typeof MLReportStartPrint == 'function') {\r\n");
      out.write("// \t\talert('st');\r\n");
      out.write("\t\tsetTimeout(\"callTimeoutFunction()\", 500);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar callTimeoutFunction = function() {\r\n");
      out.write("// \t\talert('ctf')\r\n");
      out.write("\t\tMLReportStartPrint();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
